version: '3.8'

services: 
    app:
        build:
            context: ./docker
            dockerfile: app.dockerfile
        #image: php:8-apache 
        ports: 
            - 8100:80
        volumes:
            - ./html:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        #env_file:  
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306 

volumes:
    dbdata: